name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: raspbpi
    steps:
      - uses: actions/checkout@v3
      - name: Install wireguard
        run: sudo apt-get install wireguard openresolv
      - name: Create wireguard configuration (step 1)
        run: touch $GITHUB_WORKSPACE/tunnel.conf
      - name: Create wireguard configuration (step 2)
        run: echo ${{secrets.WIREGUARD_CONFIG}} > $GITHUB_WORKSPACE/tunnel.conf
      - name: Create wireguard configuration (step 3)
        run: sudo cp $GITHUB_WORKSPACE/tunnel.conf /etc/wireguard/
      - name: Create wireguard configuration (step 4)
        run: wg-quick up tunnel
      - name: "Push to server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "/"
          strip_components: 1
          target: "/var/www/html"
