name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: raspbpi
    steps:
      - uses: actions/checkout@v3
      - name: Install wireguard
        run: sudo apt-get install wireguard openresolv
      - name: Create wireguard configuration
        run: |
          touch $GITHUB_WORKSPACE/tunnel.conf
          echo ${{secrets.WIREGUARD_CONFIG}} | base64 -d > $GITHUB_WORKSPACE/tunnel.conf
          sudo cp $GITHUB_WORKSPACE/tunnel.conf /etc/wireguard/
          wg-quick up tunnel
      - name: Set up ssh key
        run: |
          touch $GITHUB_WORKSPACE/key
          echo ${{secrets.SSH_KEY}} | base64 -d > $GITHUB_WORKSPACE/key
          chmod 600 $GITHUB_WORKSPACE/key
      - name: Transfer files
        run: scp -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/key -r . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/html
